title: christopherschoeder.me
description: Personal website for Christopher Schoeder
theme: just-the-docs
source: "_docs"
url: christopherschoeder.me
baseurl: ""
repository: squishedfox.com/christopherschoeder
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
# Set a path/url to a logo that will be displayed instead of the title
logo: "https://gravatar.com/avatar/8566d61fc0bc8d56cdfcf9e1cd4b858033039417cbbb4613108662c9c46e3c03"
