title: SquishedFox
description: Place for saving training, education, and other notes.
theme: just-the-docs
source: "_docs"
url: squishedfox-com
baseurl: ""
repository: squishedfox.com/squishedfox-com
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
# Set a path/url to a logo that will be displayed instead of the title
logo: /assets/images/logo.png
