title: christopherschoeder.me
description: Personal website for Christopher Schoeder
theme: just-the-docs
source: "_docs"
url: christopherschoeder.me
baseurl: ""
repository: squishedfox.com/christopherschoeder
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
